repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff check
        entry: ruff check --exit-non-zero-on-fix .
        language: python
        types: [python]
      - id: tests
        name: pytest
        entry: pytest tests
        language: python
        types: [python]