[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "swiftbots"
version = "0.3.0b6"
description = "Python asynchronous web framework for rapid any-level bots development"
authors = ["Polka <you@example.com>"]
readme = "docs/README.md"
repository = "https://github.com/SaberOte/SwiftBots"

[tool.poetry.dependencies]
python = ">=3.8.0"
aiohttp = "^3.0.0"

[tool.poetry.group.dev.dependencies]
ruff = "*"
aiosqlite = "*"
pytest = "*"
pytest-timeout = "*"
mypy = "*"
