[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "swiftbots"
version = "0.3.0dev"
description = "Python asynchronous web framework for rapid any-level bots development"
authors = ["Polka <you@example.com>"]
readme = "docs/README.md"
repository = "https://github.com/SaberOte/SwiftBots"

[tool.poetry.dependencies]
python = ">=3.9.0"
alembic = "^1.13.1"
aiohttp = "^3.9.2"
sqlalchemy = {extras = ["asyncio"], version = "^2.0.25"}

[tool.poetry.group.dev.dependencies]
ruff = "^0.4.7"
aiosqlite = "^0.20.0"
pytest = "^8.2.1"
pytest-timeout = "^2.3.1"
mypy = "^1.10.0"
