[tool.poetry]
name = "swiftbots"
version = "0.1.5"
description = "Python asynchronous web framework for rapid any-level bots development"
authors = ["Polka <you@example.com>"]
readme = "docs/README.md"

[tool.poetry.dependencies]
python = ">=3.10.0, <3.12"
aiohttp = "*"
alembic = "*"
sqlalchemy = {extras = ["asyncio"], version = "*"}

[tool.poetry.group.dev.dependencies]
flake8 = "*"
pylint = "*"
aiosqlite = "*"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
