[tool.poetry]
name = "swiftbots"
version = "0.1.9dev"
description = "Python asynchronous web framework for rapid any-level bots development"
authors = ["Polka <you@example.com>"]
readme = "docs/README.md"
repository = "https://github.com/Biotechrhythm/SwiftBots"

[tool.poetry.dependencies]
python = ">=3.10.0, <3.12"
alembic = "^1.13.1"
aiohttp = "^3.9.1"
sqlalchemy = {extras = ["asyncio"], version = "^2.0.25"}

[tool.poetry.group.dev.dependencies]
ruff = "^0.1.11"
aiosqlite = "^0.19.0"
pytest = "^7"
pytest-timeout = "^2.2.0"

[tool.poetry.group.test.dependencies]
pytest = "^7.4.4"
pytest-timeout = "^2.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
