line-length = 79
target-version = "py310"

[lint]
select = [
#   "ALL",
    "F",
    "I",
    "ASYNC" 
#    "E",
#    "UP",
#    "ANN"
]

[format]
indent-style = "space"


[per-file-ignores]
"__init__.py" = ["F403"]