line-length = 121
indent-width = 4
target-version = "py310"

[lint]
extend-select = [
#    "ALL",
    "F",
    "I",
    "ASYNC",
    "W",
    "E",
    "UP",
    "ANN",
    "T20",
]

ignore = [
    # annotate `self`. wtf ?????
    "ANN101",
    # annotate `__init__` ???????
    "ANN204",
    # annotate *args :/
    "ANN002",
    # annotate **kwargs ...
    "ANN003",
    # single quota demand
    "Q000",
]

[format]
indent-style = "space"
quote-style = "single"

[lint.per-file-ignores]
"__init__.py" = ["F403", "I001"]
"**/{tests,examples}/*" = ["ANN", "T201"]

#"**/{alembic}/*" = ["ALL"]